title: Tyler Lee
description: Leader // Explorer // Engineer

baseurl: ""
url: "http://tlee753.com"

email: tlee753@protonmail.com
linkedin_username: tlee753
github_username:  tlee753
dribble_username: tlee753
twitter_username: tlee753
facebook_username: Tyler Lee

# Build settings
markdown: kramdown
