title: Tyler Lee
tagline: Leader // Explorer // Engineer
description: Leader // Explorer // Engineer

baseurl: ""
url: "https://tlee753.com"

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
include: ['_pages']

host: 0.0.0.0
port: 4000

sass:
  sass_dir: css
  style: :nested
