# Site settings
title: Tyler Lee's Personal Website
email: tlee753@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/_posts/" # the subpath of your site, e.g. /blog/
url: "tlee753.com" # the base hostname & protocol for your site

twitter_username: tlee753
github_username: tlee753
linkedin_username: tlee753

# Build settings
markdown: kramdown
