# General Information
title: Tyler Lee
tagline: Leader // Explorer // Engineer
description: Leader // Explorer // Engineer


# Site Location
baseurl: ""
url: "http://tlee753.com"


# Build settings
markdown: kramdown


# Specify the port jekyll uses to serve locally
port: 4000


# Sass settings
sass:
  sass_dir: css
  style: :nested

include: ['_pages']