# General Information
title: Tyler Lee
description: Leader // Explorer // Engineer


# Site Location
baseurl: ""
url: "http://tlee753.com"


# Build settings
markdown: kramdown
permalink: pretty


# Specify the port jekyll uses to serve locally
port: 4000


# Sass settings
sass:
  sass_dir: css
  style: :nested
