# General Information
title: Tyler Lee
tagline: Leader // Explorer // Engineer
description: Leader // Explorer // Engineer


# Site Location
baseurl: "" # default base url of /
url: "http://tlee753.com"


# Build settings
markdown: kramdown
include: ['_pages']
permalink: /:title/


# Specify the port jekyll uses to serve locally
port: 4000


# Sass settings
sass:
  sass_dir: css
  style: :nested

