#-------------------------------
# Menu Section
menu:
- {name: About, link: "/about"}
- {name: Portfolio, link: "/portfolio"}
- {name: Blog, link: "/blog"}
- {name: Travel, link: "/travel"}
- {name: Contact, link: "/contact"}

#-------------------------------
# Skill Section
skills:
- {name: Communication, value: '8'}
- {name: Organization, value: '8'}
- {name: Learning, value: '9'}
- {name: Teaching, value: '8'}
- {name: Planning, value: '7'}
- {name: Visual Design, value: '6'}
- {name: UX Design, value: '6'}
- {name: Programming, value: '7'}

#-------------------------------
# Portfolio Section
portfolio:
- {name: Rocketry, folder: "rocketry"}
- {name: High Altitude Ballooning, folder: "hab"}
- {name: Interactive Robotics, folder: "interactive-robotics"}
- {name: Chess Visualizer, folder: "chess-visualizer"}
- {name: Image Manipulation, folder: "image-manipulation"}
- {name: Eagle Scout Project, folder: "eagle-scout-project"}
- {name: Performance Computers, folder: "performance-computers"}
- {name: Passive Desalinator, folder: "passive-desalinator"}

#-------------------------------
# Portfolio Page
portfoliopage:
- {name: Football Automute, folder: "football-automute"}
- {name: Angel Nonprofit, folder: "angel-nonprofit"}
- {name: Venusian Atmospheric Probe Explorer, folder: "vape"}
- {name: Vestibular Balance, folder: "vestibular-balance"}
- {name: High Altitude Balloon, folder: "hab"}
- {name: Performance Computers, folder: "performance-computers"}
- {name: Rocketry, folder: "rocketry"}
- {name: Autonomous Robotics, folder: "autonomous-robotics"}
- {name: Eagle Scout Project, folder: "eagle-scout-project"}
- {name: Chess Visualizer, folder: "chess-visualizer"}
- {name: Plane Tracker, folder: "plane-tracker"}
- {name: Rocket Core, folder: "rocket-core"}
- {name: Image Manipulation, folder: "image-manipulation"}
- {name: Web Automation Framework, folder: "web-automation-framework"}
- {name: Electrathon Vehicle, folder: "electrathon-vehicle"}
- {name: Interactive Robotics, folder: "interactive-robotics"}
- {name: Passive Desalinator, folder: "passive-desalinator"}
- {name: Web Development, folder: "web-development"}
- {name: Awol App, folder: "awol"}
- {name: Ricing, folder: "ricing"}
- {name: Text Server, folder: "text-server"}
- {name: School Projects, folder: "school-projects"}
- {name: Stock Dashboard, folder: "stock-dashboard"}
- {name: World History Timeline, folder: "world-history-timeline"}
- {name: Lifestyle Budget, folder: "lifestyle-budget"}
- {name: Personal Finance Club, folder: "finance-club"}
- {name: Homelab, folder: "homelab"}
- {name: Automated Can Crusher, folder: "automated-can-crusher"}

# - {name: Beaglebone PRU Encoder Reading, folder: "beaglebone-pru-encoder-reading"}
# - {name: Musings of a 20 Year Old, folder: "musings"}
# - {name: Keys to Happiness, folder: "keys-to-happiness"}
# Quadcopter build
# cheap astro mount

#-------------------------------
# Contact Section
social:
- {icon: "github", link: "http://www.github.com/tlee753"}
- {icon: "linkedin", link: "http://www.linkedin.com/in/tlee753"}
- {icon: "mail", link: "mailto:tlee753@gatech.edu"}

#-------------------------------
# Contact Page
socialpage:
- {icon: "github", link: "http://www.github.com/tlee753"}
- {icon: "linkedin", link: "http://www.linkedin.com/in/tlee753"}
- {icon: "mail", link: "mailto:tlee753@gatech.edu"}

#-------------------------------
# Collection Section
interests:
- {name: My Favorite Movies, folder: "movies", link: "/movies/"}
- {name: My Bucket List, folder: "bucket", link: "/bucket/"}
- {name: My Favorite Books, folder: "books", link: "/books/"}
- {name: My Favorite Quotes, folder: "quotes", link: "/quotes/"}
- {name: My Favorite TED Talks, folder: "ted", link: "/ted/"}
- {name: Wanderers, folder: "wanderers", link: "/wanderers/"}
- {name: How to Win Friends and Influence People, folder: "htwfaip", link: "https://en.wikipedia.org/wiki/How_to_Win_Friends_and_Influence_People"}
- {name: Euler Problems, folder: "euler", link: "https://projecteuler.net/"}
- {name: Intelligence Squared, folder: "intelligence-squared", link: "https://www.intelligencesquaredus.org/"}
- {name: Georgia Tech UNICEF, folder: "unicef", link: "http://www.unicef.gatech.edu/"}
- {name: Start with Why, folder: "why", link: "/why/"}
- {name: Calvin and Hobbes, folder: "calvin", link: "http://bigthink.com/Picture-This/what-is-the-legacy-of-calvin-and-hobbes"}
- {name: Albert Einstein, folder: "einstein", link: "https://es.wikipedia.org/wiki/Albert_Einstein"}
- {name: The Boy and the Starfish, folder: "starfish", link: "/starfish/"}
- {name: John Wooden, folder: "wooden", link: "http://coachwooden.com"}
- {name: Reader's Digest, folder: "readers-digest", link: "http://www.rd.com/"}

#-------------------------------
# Slider Section
slider:
- {name: "Fussen, Germany", image: "slider-fussen", link: "/germany/2017/01/22/Fussen.html"}
- {name: "Cairo, Egypt", image: "slider-cairo", link: "/egypt/2019/05/28/Cairo.html"}
- {name: "Santiago, Chile", image: "slider-santiago", link: "/chile/2016/06/21/Santiago.html"}
- {name: "Dubai, U.A.E.", image: "slider-dubai", link: "/uae/2019/06/10/Dubai.html"}
- {name: "Galapagos, Ecuador", image: "slider-galapagos", link: "/ecuador/2016/07/14/Galapagos.html"}

# - {name: "Interlaken, Switzerland", image: "slider-interlaken", link: "/switzerland/2017/02/11/Interlaken.html"}
# - {name: "Cuenca, Ecuador", image: "slider-cuenca", link: "http://tlee753.com/ecuador/2016/06/30/Cuenca.html"}
# - {name: "Munich, Germany", image: "slider-munich", link: "http://tlee753.com/germany/2017/01/21/Munich.html"}

#-------------------------------
# Search Engine Optimization
seo:
  description: "Tyler Lee's Personal Website"
  rel-author: "http://www.linkedin/in/tlee753"

#-------------------------------
# Google Analytics Section
google-analytics-ua: "UA-107927214-1"
