#-------------------------------
# Menu Section

menu:
- {name: About, link: '/about'}
- {name: Portfolio, link: '/portfolio'}
- {name: Blog, link: '/blog'}
- {name: Contact, link: '/contact'}


#-------------------------------
# Skill Section

skills:
- {name: Communication, value: '8'}
- {name: Organization, value: '8'}
- {name: Learning, value: '9'}
- {name: Teaching, value: '7'}
- {name: Planning, value: '7'}
- {name: Visual Design, value: '6'}
- {name: UX Design, value: '5'}
- {name: Programming, value: '6'}


#-------------------------------
# Portfolio Section

portfolio:
- {name: Performance Computer Build, folder: 'performance-computer-build'}
- {name: Autonomous Cargo Robot, folder: 'autonomous-cargo-robot'}
- {name: Eagle Scout Project, folder: 'eagle-scout-project'}
- {name: Stock Monitoring App, folder: 'stock-monitoring-app'}
- {name: Electrathon Vehicle, folder: 'electrathon-vehicle'}
- {name: Windows Server Technical Preview, folder: 'windows-server-technical-preview'}
- {name: Automated Can Crusher, folder: 'automated-can-crusher'}
- {name: Keys to Happiness, folder: 'keys-to-happiness'}


#-------------------------------
# Contact Section

social:
- {icon: 'github', link: 'http://www.github.com/tlee753', color: "#000000"}
- {icon: 'skype', link: 'skype:tlee753?chat', color: "#00AFF0"}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/tlee753', color: "#007BB5"}
- {icon: 'twitter', link: 'http://www.twitter.com/tlee753', color: "#55ACEE"}
- {icon: 'facebook', link: 'http://www.facebook.com/tyler.lee.14019', color: "#3B5998"}

# - {icon: 'mail', link: 'mailto:tlee753@gatech.edu', color: "#008BCF"}
# - {icon: 'microsoft', link: '', color: "#0078D7"}
# - {icon: 'stackoverflow', link: 'http://stackoverflow.com/users/5428731/tlee753?tab=profile', color: "#FE7A15"}
# - {icon: 'youtube', link: 'http://www.youtube.com/user/tlee753', color: "#BB0000"}
# - {icon: 'googleplus', link: 'http://plus.google.com/u/0/+TylerLee753', color: "#DD4B39"}


#-------------------------------
# Contact Page

socialpage:
- {icon: 'mail', link: 'mailto:tlee753@gatech.edu', color: "#008BCF"}
- {icon: 'skype', link: 'skype:tlee753?chat', color: "#00AFF0"}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/tlee753', color: "#007BB5"}
- {icon: 'github', link: 'http://www.github.com/tlee753', color: "#000000"}
- {icon: 'stackoverflow', link: 'http://stackoverflow.com/users/5428731/tlee753?tab=profile', color: "#FE7A15"}
- {icon: 'twitter', link: 'http://www.twitter.com/tlee753', color: "#55ACEE"}
- {icon: 'facebook', link: 'http://www.facebook.com/tyler.lee.14019', color: "#3B5998"}
- {icon: 'googleplus', link: 'http://plus.google.com/u/0/+TylerLee753', color: "#DD4B39"}

# - {icon: 'microsoft', link: '', color: "#0078D7"}
# - {icon: 'youtube', link: 'http://www.youtube.com/user/tlee753', color: "#BB0000"}


#-------------------------------
# Collection Section

interests:
- {name: How to Win Friends and Influence People, folder: 'coll-1', link: 'https://en.wikipedia.org/wiki/How_to_Win_Friends_and_Influence_People'}
- {name: Wanderers, folder: 'coll-2', link: '/about/wanderers/index.html'}
- {name: Start with Why, folder: 'coll-3', link: '/about/why/index.html'}
- {name: Euler Problems, folder: 'coll-4', link: 'https://projecteuler.net/'}
- {name: My Favorite Quotes, folder: 'coll-11', link: 'https://www.youtube.com/watch?v=GC7Aqc-h9no'}
- {name: Intelligence Squared, folder: 'coll-21', link: 'https://www.intelligencesquaredus.org/'}
- {name: My Favorite Movies, folder: 'coll-5', link: '/about/movies/'}
- {name: Georgia Tech UNICEF, folder: 'coll-7', link: 'http://www.unicef.gatech.edu/'}
- {name: Calvin and Hobbes, folder: 'coll-8', link: 'http://bigthink.com/Picture-This/what-is-the-legacy-of-calvin-and-hobbes'}
- {name: Stockfish vs Komodo Chess Engines, folder: 'coll-9', link: 'https://en.wikipedia.org/wiki/Top_Chess_Engine_Championship'}
- {name: The Boy and the Starfish, folder: 'coll-6', link: '/starfish/'}
- {name: TED Talks, folder: 'coll-23', link: 'https://www.ted.com'}
- {name: Albert Einstein, folder: 'coll-13', link: 'https://es.wikipedia.org/wiki/Albert_Einstein'}
- {name: Space X, folder: 'coll-14', link: 'http://www.spacex.com/'}
- {name: John Wooden, folder: 'coll-15', link: 'http://espn.go.com/mens-college-basketball/news/story?id=5249709'}
- {name: RECONSO, folder: 'coll-22', link: 'https://reconso.gatech.edu'}
- {name: John Oliver, folder: 'coll-17', link: 'https://www.youtube.com/channel/UC3XTzVzaHQEd30rQbuvCtTQ'}
- {name: Reader's Digest, folder: 'coll-18', link: 'http://www.rd.com/'}
- {name: Vsauce, folder: 'coll-19', link: 'https://www.youtube.com/channel/UC6nSFpj9HTCZ5t-N3Rm3-HA'}
- {name: GT Advice, folder: 'coll-20', link: '/gtadvice/'}

# amazon reviews
# scott sterling
# history of japan
# key and peele

# jack johnson
# formula one racing
# world war 2

# HUMOR

# - {name: Star Wars, folder: 'coll-10', link: 'http://metro.co.uk/2015/05/04/star-wars-day-18-reasons-the-original-trilogy-will-always-be-better-than-the-new-films-5179869/'}
# - {name: Dream Car, folder: 'coll-16', link: 'http://www.carmagazine.co.uk/car-reviews/audi/audi-r8-e-tron-2013-review/'}
# - {name: Coding Jokes, folder: 'coll-12', link: 'http://www.hongkiat.com/blog/programming-jokes/'}


#-------------------------------
# Slider Section

slider:
- {name: 'Interlaken, Switzerland', image: 'slider-interlaken', link: 'http://tlee753.com/switzerland/2017/02/11/Interlaken.html'}
- {name: 'Bruges, Belgium', image: 'slider-bruges', link: 'http://tlee753.com/belgium/2017/01/28/Bruges.html'}
- {name: 'Fussen, Germany', image: 'slider-fussen', link: 'http://tlee753.com/germany/2017/01/22/Fussen.html'}
- {name: 'Santiago, Chile', image: 'slider-santiago', link: 'http://tlee753.com/chile/2016/06/21/Santiago.html'}
- {name: 'Galapagos, Ecuador', image: 'slider-galapagos', link: 'http://tlee753.com/ecuador/2016/07/14/Galapagos.html'}

# - {name: 'Cuenca, Ecuador', image: 'slider-cuenca', link: 'http://tlee753.com/ecuador/2016/06/30/Cuenca.html'}
# - {name: 'Munich, Germany', image: 'slider-munich', link: 'http://tlee753.com/germany/2017/01/21/Munich.html'}

# france (mont saint michel)
# grand cayman
# niagra falls


#-------------------------------
# Search Engine Optimization

seo:
  description: 'Tyler Lee''s Personal Website'
  rel-author: 'http://www.linkedin/in/tlee753'
  rel-publisher: 'http://www.linkedin/in/tlee753'


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X
