#-------------------------------
# Menu Section
menu:
- {name: About, link: '/about'}
- {name: Portfolio, link: '/portfolio'}
- {name: Blog, link: '/blog'}
- {name: Contact, link: '/contact'}


#-------------------------------
# Skill Section
skills:
- {name: Communication, value: '8'}
- {name: Organization, value: '8'}
- {name: Learning, value: '9'}
- {name: Teaching, value: '8'}
- {name: Planning, value: '7'}
- {name: Visual Design, value: '6'}
- {name: UX Design, value: '6'}
- {name: Programming, value: '7'}


#-------------------------------
# Portfolio Section
portfolio:
- {name: Performance Computer Build, folder: 'performance-computer-build'}
- {name: Eagle Scout Project, folder: 'eagle-scout-project'}
- {name: Image Manipulation, folder: 'image-manipulation'}
- {name: Electrathon Vehicle, folder: 'electrathon-vehicle'}
- {name: Interactive Robotics, folder: 'interactive-robotics'}
- {name: Rocketry, folder: 'rocketry'}
- {name: Chess Visualizer, folder: 'chess-visualizer'}
#- {name: Stock Monitoring App, folder: 'stock-monitoring-app'}
- {name: Passive Desalinator, folder: 'passive-desalinator'}


#-------------------------------
# Portfolio Page
portfoliopage:
- {name: Performance Computer Build, folder: 'performance-computer-build', next: '', previous: ''}
- {name: Autonomous Robotics, folder: 'autonomous-robotics', next: '', previous: ''}
- {name: Eagle Scout Project, folder: 'eagle-scout-project', next: '', previous: ''}
- {name: Rocketry, folder: 'rocketry', next: '', previous: ''}
- {name: Stock Monitoring App, folder: 'stock-monitoring-app', next: '', previous: ''}
- {name: Electrathon Vehicle, folder: 'electrathon-vehicle', next: '', previous: ''}
- {name: Interactive Robotics, folder: 'interactive-robotics', next: '', previous: ''}
- {name: Chess Visualizer, folder: 'chess-visualizer', next: '', previous: ''}
- {name: Passive Desalinator, folder: 'passive-desalinator', next: '', previous: ''}
- {name: Image Manipulation, folder: 'image-manipulation', next: '', previous: ''}
- {name: Ricing, folder: 'ricing', next: '', previous: ''}
- {name: Automated Can Crusher, folder: 'automated-can-crusher', next: '', previous: ''}
- {name: Text Server, folder: 'text-server', next: '', previous: ''}
- {name: Web Development, folder: 'web-development', next: '', previous: ''}

# - {name: Beaglebone PRU Encoder Reading, folder: 'beaglebone-pru-encoder-reading', next: '', previous: ''}
# - {name: Musings of a 20 Year Old, folder: 'musings', next: '', previous: ''}
# - {name: Keys to Happiness, folder: 'keys-to-happiness', next: '', previous: ''}
# - {name: Windows Server Technical Preview, folder: 'windows-server-technical-preview', next: '', previous: ''}
# - {name: Text Server, folder: 'text-server', next: '', previous: ''}


# Web/GUI Development
# NASA Orion space capsule (open source)


#-------------------------------
# Contact Section
social:
- {icon: 'github', link: 'http://www.github.com/tlee753', color: "#000000"}
- {icon: 'skype', link: 'skype:tlee753?chat', color: "#00AFF0"}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/tlee753', color: "#007BB5"}
- {icon: 'twitter', link: 'http://www.twitter.com/tlee753', color: "#55ACEE"}
- {icon: 'facebook', link: 'http://www.facebook.com/tyler.lee.14019', color: "#3B5998"}

# - {icon: 'mail', link: 'mailto:tlee753@gatech.edu', color: "#008BCF"}
# - {icon: 'microsoft', link: '', color: "#0078D7"}
# - {icon: 'stackoverflow', link: 'http://stackoverflow.com/users/5428731/tlee753?tab=profile', color: "#FE7A15"}
# - {icon: 'youtube', link: 'http://www.youtube.com/user/tlee753', color: "#BB0000"}
# - {icon: 'googleplus', link: 'http://plus.google.com/u/0/+TylerLee753', color: "#DD4B39"}


#-------------------------------
# Contact Page
socialpage:
- {icon: 'mail', link: 'mailto:tlee753@gatech.edu', color: "#008BCF"}
- {icon: 'skype', link: 'skype:tlee753?chat', color: "#00AFF0"}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/tlee753', color: "#007BB5"}
- {icon: 'github', link: 'http://www.github.com/tlee753', color: "#000000"}
- {icon: 'stackoverflow', link: 'http://stackoverflow.com/users/5428731/tlee753?tab=profile', color: "#FE7A15"}
- {icon: 'twitter', link: 'http://www.twitter.com/tlee753', color: "#55ACEE"}
- {icon: 'facebook', link: 'http://www.facebook.com/tyler.lee.14019', color: "#3B5998"}
- {icon: 'googleplus', link: 'http://plus.google.com/u/0/+TylerLee753', color: "#DD4B39"}

# - {icon: 'microsoft', link: '', color: "#0078D7"}
# - {icon: 'youtube', link: 'http://www.youtube.com/user/tlee753', color: "#BB0000"}


#-------------------------------
# Collection Section
interests:
- {name: My Favorite Quotes, folder: 'quotes', link: '/quotes/'}
- {name: My Bucket List, folder: 'bucket', link: '/bucket/'}
- {name: My Favorite Books, folder: 'books', link: '/books/'}
- {name: My Favorite Movies, folder: 'movies', link: '/movies/'}

- {name: How to Win Friends and Influence People, folder: 'htwfaip', link: 'https://en.wikipedia.org/wiki/How_to_Win_Friends_and_Influence_People'}
- {name: Wanderers, folder: 'wanderers', link: '/wanderers/'}
- {name: Start with Why, folder: 'why', link: '/why/'}
- {name: Euler Problems, folder: 'euler', link: 'https://projecteuler.net/'}
- {name: Intelligence Squared, folder: 'intelligence-squared', link: 'https://www.intelligencesquaredus.org/'}
- {name: Georgia Tech UNICEF, folder: 'unicef', link: 'http://www.unicef.gatech.edu/'}
- {name: The Boy and the Starfish, folder: 'starfish', link: '/starfish/'}
- {name: Calvin and Hobbes, folder: 'calvin', link: 'http://bigthink.com/Picture-This/what-is-the-legacy-of-calvin-and-hobbes'}
- {name: Albert Einstein, folder: 'einstein', link: 'https://es.wikipedia.org/wiki/Albert_Einstein'}
- {name: TED Talks, folder: 'ted', link: 'https://www.ted.com'}
- {name: John Wooden, folder: 'wooden', link: 'http://coachwooden.com'}
- {name: Reader's Digest, folder: 'readers-digest', link: 'http://www.rd.com/'}

# - {name: John Oliver, folder: 'oliver', link: 'https://www.youtube.com/channel/UC3XTzVzaHQEd30rQbuvCtTQ'}
# - {name: Space X, folder: 'spacex', link: 'http://www.spacex.com/'}
# - {name: RECONSO, folder: 'reconso', link: 'https://reconso.gatech.edu'}
# - {name: Vsauce, folder: 'vsauce', link: 'https://www.youtube.com/channel/UC6nSFpj9HTCZ5t-N3Rm3-HA'}

# HUMOR SECTION
# amazon reviews
# scott sterling
# history of japan
# key and peele

# IDEAS
# jack johnson
# formula one racing
# world war 2

# OTHER
# - {name: Star Wars, folder: 'star-wars', link: 'http://metro.co.uk/2015/05/04/star-wars-day-18-reasons-the-original-trilogy-will-always-be-better-than-the-new-films-5179869/'}
# - {name: Dream Car, folder: 'dream-car', link: 'http://www.carmagazine.co.uk/car-reviews/audi/audi-r8-e-tron-2013-review/'}
# - {name: Coding Jokes, folder: 'coding-jokes', link: 'http://www.hongkiat.com/blog/programming-jokes/'}
# - {name: Stockfish vs Komodo Chess Engines, folder: 'chess', link: 'https://en.wikipedia.org/wiki/Top_Chess_Engine_Championship'}


#-------------------------------
# Slider Section
slider:
- {name: 'Interlaken, Switzerland', image: 'slider-interlaken', link: 'http://tlee753.com/switzerland/2017/02/11/Interlaken.html'}
- {name: 'Bruges, Belgium', image: 'slider-bruges', link: 'http://tlee753.com/belgium/2017/01/28/Bruges.html'}
- {name: 'Fussen, Germany', image: 'slider-fussen', link: 'http://tlee753.com/germany/2017/01/22/Fussen.html'}
- {name: 'Santiago, Chile', image: 'slider-santiago', link: 'http://tlee753.com/chile/2016/06/21/Santiago.html'}
- {name: 'Galapagos, Ecuador', image: 'slider-galapagos', link: 'http://tlee753.com/ecuador/2016/07/14/Galapagos.html'}

# - {name: 'Cuenca, Ecuador', image: 'slider-cuenca', link: 'http://tlee753.com/ecuador/2016/06/30/Cuenca.html'}
# - {name: 'Munich, Germany', image: 'slider-munich', link: 'http://tlee753.com/germany/2017/01/21/Munich.html'}

# france (mont saint michel)
# grand cayman
# niagra falls


#-------------------------------
# Search Engine Optimization
seo:
  description: 'Tyler Lee''s Personal Website'
  rel-author: 'http://www.linkedin/in/tlee753'
  rel-publisher: 'http://www.linkedin/in/tlee753'


#-------------------------------
# Google Analytics Section
# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065
# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.
google-analytics-ua: "UA-107927214-1"
