#-------------------------------
# Menu Section

menu:
- {name: About, link: 'about'}
- {name: Portfolio, link: 'www.tlee753.com'}
- {name: Blog, link: 'www.tlee753.com'}
- {name: Contact, link: 'www.linkedin.com/in/tlee753'}


#-------------------------------
# About Section

about: >
  **I enjoy intertwining my creativity with complex problem solving,
  whether it's coding, computer building, graphic design, 3D printing, laser engraving, welding, or web development.
  My passion stems from an unrelenting desire to learn more, and the hope that I can change the world for the better.

#  **Travis specializes in making things** for human people.
#  Most of the things he makes are [digital interfaces](http://travisneilson.com){:target="_blank"},
#  but he also puts effort into crafting [next-level beats](http://soundcloud.com/travis-neilson){:target="_blank"}
#  and [YouTube videos](http://youtube.com/user/devtipsfordesigners){:target="_blank"} about making codes happen.


#-------------------------------
# Skill Section

skills:
- {name: Communication, value: '8'}
- {name: Organization, value: '8'}
- {name: Learning, value: '9'}
- {name: Teaching, value: '7'}
- {name: Planning, value: '7'}
- {name: Visual Design, value: '6'}
- {name: UX Design, value: '5'}
- {name: Programming, value: '6'}


#-------------------------------
# Work Section

projects:
- {name: Ascension Computer Build, folder: 'proj-1'}
- {name: Autonomous Cargo Robot, folder: 'proj-2'}
- {name: Eagle Scout Project, folder: 'proj-3'}
- {name: Electrathon Vehicle, folder: 'proj-4'}
- {name: Automated Can Crusher, folder: 'proj-5'}
- {name: Windows Server Technical Preview, folder: 'proj-6'}
- {name: Cross Platform Stock Monitoring App, folder: 'proj-7'}
- {name: Keys to Happiness, folder: 'proj-8'}


#-------------------------------
# Contact Section

social:
- {icon: 'github', link: 'http://www.github.com/tlee753'}
- {icon: 'linkedin', link: 'https://www.linkedin/in/tlee753'}
- {icon: 'email', link: 'tlee753@gatech.edu'}
- {icon: 'twitter', link: 'https://www.twitter.com/tlee753'}
- {icon: 'facebook', link: 'http://www.facebook.com/'}


#-------------------------------
# Collection Section

interests:
- {name: How to Win Friends and Influence People, folder: 'coll-1'}
- {name: Wanderers, folder: 'coll-2'}
- {name: Start with Why, folder: 'coll-3'}
- {name: Euler Problems, folder: 'coll-4'}
- {name: My Favorite Movies, folder: 'coll-5'}
- {name: The Boy and the Starfish, folder: 'coll-6'}
- {name: UNICEF, folder: 'coll-7'}
- {name: Calvin and Hobbes, folder: 'coll-8'}


#-------------------------------
# Search Engine Optimization

seo:
  description: 'Tyler Lee''s Personal Website'
  rel-author: 'https://plus.google.com/u/0/+DevTipsForDesigners/'
  rel-publisher: 'https://plus.google.com/u/0/+DevTipsForDesigners/'


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X
